name: create_gdocs_microservice
description: A microservice for creating google docs as the authenticated user.
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  functions_framework: any
  shelf: any
  http: any
  json_annotation: any
  freezed_annotation: any
  googleapis: any
  googleapis_auth: any

dev_dependencies:
  build_runner: any
  functions_framework_builder: 
    git: 
      url: https://github.com/nickmeinhold/functions-framework-dart.git
      path: functions_framework_builder
      ref: include-mixins-in-builder-tojson-check
  freezed: any
  json_serializable: any
  test: any
  test_process: any
  mockito: any